language: ruby
rvm:
  - 2.3.1

env:
  global:
  - ENCRYPTION_LABEL: "195bd079f767"
  - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"
  - TRIGGER_REPO_SLUG: "patternfly/patternfly-org"
  - TRIGGER_REPO_BRANCH: "master"

before_install:
  - gem install jekyll -v 3.1.6
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install -g bower grunt-cli
  - npm install git+https://github.com/patternfly/patternfly-eng-release.git

install: true

script:
  - sh -x ./node_modules/patternfly-eng-release/scripts/_build.sh -o

after_success:
  - grunt build
  - ./scripts/publish-ghpages.sh -t -w -r "git@github.com:patternfly/patternfly.github.io.git" -b master _site

deploy:
  provider: openshift
  user: "$OPENSHIFT_USER"
  password: "$OPENSHIFT_PWD"
  domain: "patternfly"
  app: v2
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_REPO_SLUG = "patternfly/patternfly-org"
