language: ruby
rvm:
  - 2.2

before_install:
  - 'npm install -g bower grunt-cli'
  - 'gem install jekyll'

script:
  - 'git checkout master'
  - 'npm install'
  - 'bower install'
  - 'grunt'

after_success:
  - sh -x ./publish.sh

branches:
  only:
    - master
