language: ruby
rvm:
  - 2.3.1

env:
  global:
  - ENCRYPTION_LABEL: "195bd079f767"
  - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"

before_install:
  - 'git checkout -B $TRAVIS_BRANCH' # Reconcile detached HEAD
  - 'npm install -g bower grunt-cli'
  - 'gem install jekyll -v 3.1.6'

script:
  - 'npm install'
  - 'bower install'
  - 'grunt'

after_success:
  - sh -x ./scripts/publish.sh
  - ./scripts/publish-ghpages.sh -w -r "git@github.com:patternfly/patternfly.github.io.git" -b master _site

deploy:
  provider: openshift
  user: "$OPENSHIFT_USER"
  password: "$OPENSHIFT_PWD"
  domain: "patternfly"
  app: v2
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_REPO_SLUG = "patternfly/patternfly-org"
