version: 2
jobs:
  build:
    branches:
        ignore:
          - master
    docker:
      - image: circleci/ruby:2.4.1-jessie-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update old stuff
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
            export PATH=$HOME/.yarn/bin:$PATH
            curl -sSL "https://nodejs.org/dist/v8.15.0/node-v8.15.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v8.15.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Sanity
          command: |
            yarn -v
            npm -v
            ruby -v
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build Site
          command: yarn build
      - run:
          name: Deploy Docs
          command: if [ -n "$CIRCLE_PULL_REQUEST" ]; then .circleci/upload_preview.sh; fi
