version: 2
jobs:
  build:
    branches:
        ignore:
          - master
    docker:
      - image: circleci/ruby:2.4.1-jessie-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Sanity
          command: |
            yarn -v
            npm -v
            ruby -v
      - run:
          name: Conditional install
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
            export PATH=$HOME/.yarn/bin:$PATH
            yarn install
      - run:
          name: Build Site
          command: yarn build
      - run:
          name: Deploy Docs
          command: if [ -n "$CIRCLE_PULL_REQUEST" ]; then .circleci/upload_preview.sh; fi
